server:
  port: 8080
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
msi:
  member:
    default-days: 180
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT}
    bucket: ${ALIYUN_OSS_BUCKET}
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    host: ${ALIYUN_OSS_HOST}
wechat:
  miniapp:
    appid: ${WECHAT_MINIAPP_APPID}
    secret: ${WECHAT_MINIAPP_SECRET}
  pay:
    mchid: ${WECHAT_PAY_MCHID}
    api-v3-key: ${WECHAT_PAY_API_V3_KEY}
    merchant-serial-number: ${WECHAT_PAY_MERCHANT_SERIAL_NUMBER}
    private-key-path: ${WECHAT_PAY_PRIVATE_KEY_PATH}
    notify-url: ${WECHAT_PAY_NOTIFY_URL}
    public-key-id: ${WECHAT_PAY_PUBLIC_KEY_ID}
    public-key-path: ${WECHAT_PAY_PUBLIC_KEY_PATH}
image:
    host: ${IMAGE_HOST}
yunpian:
  sms:
    apikey: ${YUNPIAN_APIKEY}
    text-template: ${YUNPIAN_TEXT_TEMPLATE:【济南赛赞】感谢您注册赛赞巡机宝，您的验证码是%s（5分钟内有效，如非本人操作，请忽略）}
aj:
  captcha:
    type: default
    cache-type: redis
    water-mark: 美机汇
    slip-offset: 5
    aes-status: true
wecom:
  webhook:
    url: ${WECOM_WEBHOOK_URL:}
  stats:
    webhook:
      url: ${WECOM_STATS_WEBHOOK_URL:}
    token: ${WECOM_STATS_TOKEN:}
