
CREATE TABLE `daily_statistics` (
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `daily_active_users` int DEFAULT 0 COMMENT '每日有效用户打开小程序的用户数',
  `new_merchant_count` int DEFAULT 0 COMMENT '每日新增商户数量',
  `total_merchant_count` int DEFAULT 0 COMMENT '每日商户总数',
  `new_valid_merchant_count` int DEFAULT 0 COMMENT '新增有效商户数量',
  `total_valid_merchant_count` int DEFAULT 0 COMMENT '截止当日有效商户总数',
  `new_product_new_count` int DEFAULT 0 COMMENT '新机当日新增上架总数',
  `new_product_new_user_count` int DEFAULT 0 COMMENT '新机新用户当日新增上架总数',
  `new_product_old_user_count` int DEFAULT 0 COMMENT '新机老用户当日新增上架总数',
  `new_product_update_count` int DEFAULT 0 COMMENT '新机当日更新上架总数',
  `new_product_new_user_update_count` int DEFAULT 0 COMMENT '新机新用户当日更新上架总数',
  `new_product_old_user_update_count` int DEFAULT 0 COMMENT '新机老用户当日更新上架总数',
  `new_product_total_count` int DEFAULT 0 COMMENT '新机截止当日总上架数',
  `new_product_total_off_count` int DEFAULT 0 COMMENT '新机截止当日未上架数',
  `new_product_buy_count` int DEFAULT 0 COMMENT '新机截止当日求购总数',
  `second_hand_product_new_count` int DEFAULT 0 COMMENT '二手机当日新增上架总数',
  `second_hand_product_new_user_count` int DEFAULT 0 COMMENT '二手机新用户当日新增上架总数',
  `second_hand_product_old_user_count` int DEFAULT 0 COMMENT '二手机老用户当日新增上架总数',
  `second_hand_product_update_count` int DEFAULT 0 COMMENT '二手机当日更新上架总数',
  `second_hand_product_new_user_update_count` int DEFAULT 0 COMMENT '二手机新用户当日更新上架总数',
  `second_hand_product_old_user_update_count` int DEFAULT 0 COMMENT '二手机老用户当日更新上架总数',
  `second_hand_product_total_count` int DEFAULT 0 COMMENT '二手机截止当日总上架数',
  `second_hand_product_total_off_count` int DEFAULT 0 COMMENT '二手机截止当日未上架数',
  `second_hand_product_buy_count` int DEFAULT 0 COMMENT '二手机截止当日求购总数',
  `call_count_product` int DEFAULT 0 COMMENT '当日商家上架产品沟通次数',
  `call_count_buy` int DEFAULT 0 COMMENT '当日商家求购产品沟通次数',
  `call_merchant_count_product` int DEFAULT 0 COMMENT '当日商家上架产品沟通商户数',
  `call_merchant_count_buy` int DEFAULT 0 COMMENT '当日商家求购产品沟通商户数',
  `daily_sign_in_count` int DEFAULT 0 COMMENT '当日签到数量',
  `daily_recharge_count` int DEFAULT 0 COMMENT '当日充值次数',
  `total_recharge_amount` bigint DEFAULT 0 COMMENT '截止当天总共充值金额',
  `daily_recharge_amount` bigint DEFAULT 0 COMMENT '当日充值金额',
  `daily_new_member_count` int DEFAULT 0 COMMENT '当日新增会员数',
  `total_member_count` int DEFAULT 0 COMMENT '截止当天总会员数',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`statistics_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='每日统计报表';
